image: python:3.6.6

clone:
  depth: 1

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - git push heroku master
